version: '3'

services:

  git-server:
    image: rittelle/git-server
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - keys:/git-server/keys
    - repos:/git-server/repos

volumes:
  keys:
  repos:
